version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: thelastfork_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d thelastfork_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password

  user-service:
    build: ./userservice
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/thelastfork_db
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PASSWORD=password
      - JWT_SECRET=thisisafakejwtforlocaldeployment234567ujhgtr567uijhgftre
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  product-service:
    build: ./productservice
    container_name: product-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/thelastfork_db
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PASSWORD=password
      - JWT_SECRET=thisisafakejwtforlocaldeployment234567ujhgtr567uijhgftre
    depends_on:
      postgres:
        condition: service_healthy

  forecast-service:
    build: ./forecastservice
    container_name: forecast-service
    ports:
      - "5000:5000"

  api-gateway:
    build: ./apigateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - JWT_SECRET=thisisafakejwtforlocaldeployment234567ujhgtr567uijhgftre
    depends_on:
      - user-service
      - product-service
      - forecast-service

  frontend:
    build: ./websitefrontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - api-gateway